name: Build for Windows x64

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Git clone
        uses: actions/checkout@v4

      - name: Build
        run: |
          ./build.bat
